const GAMES = [
    {
        name: 'WirePlanet',
        genre: '2Dシューティング',
        version: [1, 2, 0],
        releaseDate: [2014, 11, 8],
        updateDate: [2017, 12, 20],
        description: '線でできた世界で、迫ってくる敵から惑星を守るシンプルなシューティングゲーム。',
        platforms: ['Windows'],
        thumbnails: ['games/wire_planet/graphics/wp_title_sc.png', 'games/wire_planet/graphics/wp_sample_sc.png'],
        url: 'games/wire_planet',
        state: GAME_STATE_RELEASED,
    }, {
        name: '伸縮性の高い石頭少女いしあたまーるちゃん',
        genre: '2Dアクション',
        version: [2, 1, 0],
        releaseDate: [2015, 5, 10],
        updateDate: [2015, 8, 18],
        description: '伸縮性の高い石頭少女を操作して上から落ちてくる岩を破壊するだけの謎のゲーム。',
        platforms: ['Android', 'Windows'],
        thumbnails: ['games/ishiatamachan/android_sc0.png', 'games/ishiatamachan/android_sc2.png', 'games/ishiatamachan/android_sc1.png'],
        url: '',
        state: GAME_STATE_RELEASED,
    }, {
        name: '逼迫性の高いだんごむし少女だんごむしむしむしむっしちゃん',
        genre: '見下ろし2Dアクション',
        version: [1, 0, 0],
        releaseDate: [2016, 1, 18],
        updateDate: [2016, 1, 18],
        description: '寿命の迫っただんごむしの少女を操作して、逃げていくわらじむし共を爆殺するだけの謎のゲーム。',
        platforms: ['Windows'],
        thumbnails: ['games/dangomushichan/screen_shot_1.jpg', 'games/dangomushichan/screen_shot_0.jpg', 'games/dangomushichan/screen_shot_2.jpg'],
        url: '',
        state: GAME_STATE_RELEASED,
    }, {
        name: '飛行可能性を得た石頭少女いしあたまーるちゃん',
        genre: '2Dアクション',
        version: [1, 0, 0],
        releaseDate: [2016, 10, 16],
        updateDate: [2016, 10, 16],
        description: '空飛ぶ石頭少女を操作して、上から落ちてくる岩や鉄球を破壊するだけの謎のゲーム。',
        platforms: ['Windows'],
        thumbnails: ['games/ishiatamachan2/isiatama2_ss_title.png', 'games/ishiatamachan2/isiatama2_ss_2.png', 'games/ishiatamachan2/isiatama2_ss_1.png'],
        url: '',
        state: GAME_STATE_RELEASED,
    }, {
        name: '10円玉工場で働こう！',
        genre: 'シミュレーション',
        version: [2, 0, 1],
        releaseDate: [2018, 11, 25],
        updateDate: [2018, 11, 26],
        description: 'ベルトコンベアで流れてくる10円玉からひたすら不良品を選別する虚無なゲーム。Unity 1Week GameJamで出したもの。',
        platforms: ['ブラウザ'],
        thumbnails: ['games/10yen_coin_factory/10yen_coin_factory_ss_0.jpg', 'games/10yen_coin_factory/10yen_coin_factory_ss_1.jpg', 'games/10yen_coin_factory/10yen_coin_factory_ss_2.jpg'],
        url: 'https://unityroom.com/games/10yencoinfactory',
        state: GAME_STATE_RELEASED,
    }, {
        name: '光影の塔',
        genre: '3Dシューティング',
        version: [0, 14, 0],
        releaseDate: [2021, 9],
        description: '光の中を駆け巡る！　爽快感満載のオンライン対戦型3Dシューティングゲーム。',
        platforms: ['Windows', 'MacOS X'],
        thumbnails: [],
        url: '',
        state: GAME_STATE_DEVELOPING,
    }, {
        name: '地獄に落ちたきりたんぽ',
        genre: '2Dアクション',
        version: [0, 0, 0],
        releaseDate: [2021, 7],
        description: '地獄に落ちたきりたんぽが、道中のちくわを踏みつぶしてドーナツにしながら現世を目指して上へ登っていく謎のゲーム。',
        platforms: ['ブラウザ', 'Windows'],
        thumbnails: [],
        url: '',
        state: GAME_STATE_DEVELOPING,
    }
];